### ISSUE TITLE
`cred` (extract def) seems to always fail with "Namespaced keywords not supported !"

### ISSUE THREAD

**Issue by daveyarwood** [clojure-vim/clj-refactor.nvim#19]
Maybe I'm just not understanding how this feature works, but I can't seem to get it to do anything except for throw this error:

```
Namespaced keywords not supported !
```

I was able to get `cref` (extract fn) to work, FWIW.

**Comment by SevereOverfl0w** [comment]
That error is if you have `::foo` in your file.

**Comment by SevereOverfl0w** [comment]
Reference: https://github.com/rundis/rewrite-cljs/issues/14

**Comment by daveyarwood** [comment]
Aha -- I think that was indeed the case for the file I was testing earlier.

I just tried it in a file that has no namespaced keywords and it worked as expected. :+1: 

Seems like once that issue is fixed upstream, it will likely trickle down into clj-refactor. :)
