### ISSUE TITLE
neovim api changes

### ISSUE THREAD

**Issue by snoe** [clojure-vim/clj-refactor.nvim#9]
Thanks to @markwoodhall for pointing this out on slack. neovim api has changed in a seemingly non-compatible way around https://github.com/neovim/neovim/commit/1c22cab2fd283db49bfdbeaea490747574a36049 (possibly earlier). I've raised an issue upstream with node-host to track this https://github.com/neovim/node-host/issues/17 .  

Until then, I'm guessing https://github.com/neovim/neovim/commit/e968d72cae57180921ad9cf24cde74fedc8b03d3#diff-dbc90d97de125c32609c02bc24e2cabf should be a safe-ish build point unfortunately I don't have the bandwidth to do a full bisect of the issue.

**Comment by justinmk** [comment]
We were careful to maintain backwards-compatibility. The `nvim_` prefix is recommended and the old methods are deprecated but still supported. But if something broke, please let us know.

**Comment by snoe** [comment]
@justinmk it looks like neovim/node-client had been updated in https://github.com/neovim/node-client/commit/c9725b34ce15a045f0bbffa975a3aa524b727684 which broke compatibility with neovim/node-host - that might be the only problem it's just getting hard to track these transitive dependencies

**Comment by snoe** [comment]
@markwoodhall upstream issues should be resolved, make sure to update node-host and deps in your nvim bundle dir. Please reach out if you're still having trouble running the plugin.

**Comment by markwoodhall** [comment]
Thanks for investigating this, I started by updating node-host and now I've created my setup again from scratch. In both instances, when I open a clojure buffer I'm getting the message below:

![screen shot 2016-10-05 at 08 08 05](https://cloud.githubusercontent.com/assets/893173/19104151/df559c5c-8ad2-11e6-8920-ba0e25b9e6ff.png)

If I ignore that and try to a run a `cref` to extract a function, after entering the function name and pressing enter I get the error below:

![screen shot 2016-10-05 at 08 08 54](https://cloud.githubusercontent.com/assets/893173/19104174/0361878c-8ad3-11e6-8fd6-69832bbf2498.png)

Having said that, I've tried a number of other operations that work fine now, for example `cril`, `crml`, `cred`.
